services:
  - type: web
    name: oscar-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DB_HOST
        value: sql.freedb.tech
      - key: DB_USER
        value: freedb_y_kilany
      - key: DB_PASSWORD
        value: P7QNvQ?sHy$z837
      - key: DB_NAME
        value: freedb_OscarProject